name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.15.x
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dwonload module
        run: go mod download

      - name: go vet
        run: go vet -v ./...

      - name: run test
        run: go test -v ./...

      - name: build
        run: go build -v
