name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dwonload module
        run: go mod download

      - name: go vet
        run: go vet -v ./...

      - name: run test
        run: go test -v ./...

      - name: build
        run: go build -v
